CREATE TABLE public.cars (
                             id bigint NOT NULL,
                             brand character varying(255),
                             model character varying(255),
                             total_seats integer,
                             year_manufacture integer,
                             car_id bigint
);


ALTER TABLE public.cars OWNER TO najdiprevoz;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: cities; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.cities (
                               id bigint NOT NULL,
                               name character varying(255)
);


ALTER TABLE public.cities OWNER TO najdiprevoz;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

--
-- Name: member_preferences; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.member_preferences (
                                           id bigint NOT NULL,
                                           is_pet_allowed boolean,
                                           is_smoking_allowed boolean
);


ALTER TABLE public.member_preferences OWNER TO najdiprevoz;

--
-- Name: member_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.member_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_preferences_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: members; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.members (
                                id bigint NOT NULL,
                                birth_date timestamp without time zone NOT NULL,
                                email character varying(255) NOT NULL,
                                first_name character varying(255) NOT NULL,
                                gender character varying(255) NOT NULL,
                                last_name character varying(255) NOT NULL,
                                password character varying(255) NOT NULL,
                                phone_number character varying(255) NOT NULL,
                                profile_photo character varying(255) NOT NULL,
                                preference_id bigint
);


ALTER TABLE public.members OWNER TO najdiprevoz;

--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: ride_requests; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.ride_requests (
                                      id bigint NOT NULL,
                                      created_on timestamp without time zone,
                                      status character varying(255),
                                      city_from bigint NOT NULL,
                                      city_to bigint NOT NULL,
                                      requester_id bigint,
                                      ride_id bigint NOT NULL
);


ALTER TABLE public.ride_requests OWNER TO najdiprevoz;

--
-- Name: ride_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.ride_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_requests_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: rides; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.rides (
                              id bigint NOT NULL,
                              description character varying(255),
                              created_on timestamp without time zone,
                              departure_time timestamp without time zone,
                              is_finished boolean,
                              price_per_head integer,
                              total_seats integer,
                              to_location character varying(255),
                              driver_id bigint NOT NULL,
                              from_location character varying(255)
);


ALTER TABLE public.rides OWNER TO najdiprevoz;

--
-- Name: rides_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.rides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rides_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );



ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--


--
-- Name: member_preferences member_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.member_preferences
    ADD CONSTRAINT member_preferences_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: ride_requests ride_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT ride_requests_pkey PRIMARY KEY (id);


--
-- Name: rides rides_pkey; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT rides_pkey PRIMARY KEY (id);


--
-- Name: cities uk_l61tawv0e2a93es77jkyvi7qa; Type: CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT uk_l61tawv0e2a93es77jkyvi7qa UNIQUE (name);


--
-- Name: ride_requests fk4mlf748wvd1c16p2at7mkux39; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fk4mlf748wvd1c16p2at7mkux39 FOREIGN KEY (ride_id) REFERENCES public.rides(id);


--
-- Name: ride_requests fkbhe7ehymbljgen3amgx4yuaq3; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fkbhe7ehymbljgen3amgx4yuaq3 FOREIGN KEY (city_from) REFERENCES public.cities(id);


--
-- Name: ride_requests fkbkdl4ehkn4pvuyhx4ura1g330; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fkbkdl4ehkn4pvuyhx4ura1g330 FOREIGN KEY (city_to) REFERENCES public.cities(id);


--
-- Name: rides fkgco6pwrgn8co7gwyludy1nnc1; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT fkgco6pwrgn8co7gwyludy1nnc1 FOREIGN KEY (from_location) REFERENCES public.cities(name);


--
-- Name: cars fkn2dpag4knu0mmplc90tuurkr; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fkn2dpag4knu0mmplc90tuurkr FOREIGN KEY (car_id) REFERENCES public.members(id);


--
-- Name: rides fko62n3qexfjtslknusqfjfcs2p; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT fko62n3qexfjtslknusqfjfcs2p FOREIGN KEY (to_location) REFERENCES public.cities(name);


--
-- Name: ride_requests fkoc5uj7y01drryd0itrmnkk1kf; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fkoc5uj7y01drryd0itrmnkk1kf FOREIGN KEY (requester_id) REFERENCES public.members(id);


--
-- Name: rides fkq0n68ras6f40ck5lqccd3v75n; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT fkq0n68ras6f40ck5lqccd3v75n FOREIGN KEY (driver_id) REFERENCES public.members(id);


--
-- Name: members fkspraixkj6bxrylrmoxmdd1iqe; Type: FK CONSTRAINT; Schema: public; Owner: najdiprevoz
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT fkspraixkj6bxrylrmoxmdd1iqe FOREIGN KEY (preference_id) REFERENCES public.member_preferences(id);