CREATE TABLE public.cars (
                             id bigint NOT NULL,
                             brand character varying(255),
                             model character varying(255),
                             total_seats integer,
                             year_manufacture integer,
                             owner_id bigint
);


ALTER TABLE public.cars OWNER TO najdiprevoz;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: cities; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.cities (
                               id bigint NOT NULL,
                               name character varying(255)
);


ALTER TABLE public.cities OWNER TO najdiprevoz;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: member_preferences; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.member_preferences (
                                           id bigint NOT NULL,
                                           is_pet_allowed boolean,
                                           is_smoking_allowed boolean,
                                           member_id bigint
);


ALTER TABLE public.member_preferences OWNER TO najdiprevoz;

--
-- Name: member_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.member_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_preferences_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: members; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.members (
                                id bigint NOT NULL,
                                birth_date timestamp without time zone NOT NULL,
                                email character varying(255) NOT NULL,
                                first_name character varying(255) NOT NULL,
                                gender character varying(255) NOT NULL,
                                last_name character varying(255) NOT NULL,
                                password character varying(255) NOT NULL,
                                phone_number character varying(255) NOT NULL,
                                profile_photo character varying(255)
);


ALTER TABLE public.members OWNER TO najdiprevoz;

--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: ratings; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.ratings (
                                id bigint NOT NULL,
                                date_submitted timestamp without time zone,
                                note character varying(255),
                                author_id bigint NOT NULL,
                                ride_id bigint NOT NULL
);


ALTER TABLE public.ratings OWNER TO najdiprevoz;

--
-- Name: ratings_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- Name: ride_requests; Type: TABLE; Schema: public; Owner: najdiprevoz
--

CREATE TABLE public.ride_requests (
                                      id bigint NOT NULL,
                                      created_on timestamp without time zone,
                                      status character varying(255),
                                      city_from bigint NOT NULL,
                                      city_to bigint NOT NULL,
                                      requester_id bigint,
                                      ride_id bigint NOT NULL
);


ALTER TABLE public.ride_requests OWNER TO najdiprevoz;

--
-- Name: ride_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: najdiprevoz
--

ALTER TABLE public.ride_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_requests_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

CREATE TABLE public.rides (
                              id bigint NOT NULL,
                              description character varying(255),
                              created_on timestamp without time zone,
                              departure_time timestamp without time zone,
                              is_finished boolean,
                              price_per_head integer,
                              total_seats integer,
                              to_location character varying(255),
                              driver_id bigint NOT NULL,
                              from_location character varying(255)
);


ALTER TABLE public.rides OWNER TO najdiprevoz;

ALTER TABLE public.rides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rides_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.member_preferences
    ADD CONSTRAINT member_preferences_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT ratings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT ride_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT rides_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT uk_l61tawv0e2a93es77jkyvi7qa UNIQUE (name);

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fk4mlf748wvd1c16p2at7mkux39 FOREIGN KEY (ride_id) REFERENCES public.rides(id);

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fkbhe7ehymbljgen3amgx4yuaq3 FOREIGN KEY (city_from) REFERENCES public.cities(id);

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fkbkdl4ehkn4pvuyhx4ura1g330 FOREIGN KEY (city_to) REFERENCES public.cities(id);

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT fkgco6pwrgn8co7gwyludy1nnc1 FOREIGN KEY (from_location) REFERENCES public.cities(name);

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT fkm9dna12woo9bxuhtbdlhek4al FOREIGN KEY (owner_id) REFERENCES public.members(id);

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT fko62n3qexfjtslknusqfjfcs2p FOREIGN KEY (to_location) REFERENCES public.cities(name);

ALTER TABLE ONLY public.ride_requests
    ADD CONSTRAINT fkoc5uj7y01drryd0itrmnkk1kf FOREIGN KEY (requester_id) REFERENCES public.members(id);

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fkpn9mvopg00wpfi5xti2wf3p1s FOREIGN KEY (ride_id) REFERENCES public.rides(id);

ALTER TABLE ONLY public.rides
    ADD CONSTRAINT fkq0n68ras6f40ck5lqccd3v75n FOREIGN KEY (driver_id) REFERENCES public.members(id);

ALTER TABLE ONLY public.member_preferences
    ADD CONSTRAINT fkr36s4dryxkuqc91v9bfl7nxc7 FOREIGN KEY (member_id) REFERENCES public.members(id);

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fks922wdjjs39auw6ac4nd8tgfb FOREIGN KEY (author_id) REFERENCES public.members(id);