CREATE TABLE public.authorities
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    authority varchar(30) UNIQUE                               NOT NULL
);

alter table public.authorities
    owner to najdiprevoz;

CREATE TABLE public.cities
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name character varying(255)
);

ALTER TABLE public.cities
    OWNER TO najdiprevoz;

CREATE TABLE public.users
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    birth_date    timestamp without time zone                      NOT NULL,
    username      character varying(255)                           NOT NULL UNIQUE,
    first_name    character varying(255)                           NOT NULL,
    gender        character varying(255)                           NOT NULL,
    last_name     character varying(255)                           NOT NULL,
    password      character varying(255)                           NOT NULL,
    phone_number  character varying(255)                           NOT NULL,
    authority_id  bigint                                           NOT NULL REFERENCES public.authorities (id),
    profile_photo TEXT,
    default_lang  TEXT,
    registered_on timestamp with time zone NOT NULL
);


ALTER TABLE public.users
    OWNER TO najdiprevoz;


CREATE TABLE public.cars
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    brand            character varying(255),
    model            character varying(255),
    total_seats      integer,
    year_manufacture integer,
    owner_id         bigint                                           not null references public.users (id)
);

ALTER TABLE public.cars
    OWNER TO najdiprevoz;


CREATE TABLE public.rides
(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description         character varying(255),
    created_on          timestamp without time zone,
    departure_time      timestamp without time zone,
    price_per_head      integer,
    total_seats_offered integer,
    to_location         bigint REFERENCES public.cities (id),
    driver_id           bigint                                           NOT NULL REFERENCES public.users (id),
    from_location       bigint REFERENCES public.cities (id),
    status              varchar(255),
    is_smoking_allowed  boolean,
    is_pet_allowed      boolean,
    has_air_condition   boolean,
    max_two_backseat    boolean
);


ALTER TABLE public.rides
    OWNER TO najdiprevoz;

CREATE TABLE public.ride_requests
(
    id                     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created_on             timestamp without time zone,
    status                 character varying(255),
    requester_id           bigint,
    ride_id                bigint                                           NOT NULL references public.rides (id),
    additional_description TEXT,
    requested_seats        int                                              NOT NULL
);

ALTER TABLE public.ride_requests
    OWNER TO najdiprevoz;

CREATE TABLE public.ratings
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    date_submitted  timestamp without time zone,
    note            character varying(255),
    rating          integer                                          NOT NULL,
    ride_request_id bigint                                           NOT NULL references public.ride_requests (id),
    rated_user      bigint                                           NOT NULL references public.users (id)

);


ALTER TABLE public.ratings
    OWNER TO najdiprevoz;


create table notifications
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created_on      timestamp,
    from_id         bigint                                           not null REFERENCES public.users (id),
    to_id           bigint                                           not null REFERENCES public.users (id),
    seen            boolean                                          not null,
    type            varchar(255),
    ride_request_id bigint                                           not null REFERENCES public.ride_requests (id)
);

alter table notifications
    owner to najdiprevoz;

create table notification_actions
(
    notification_id bigint not null references notifications (id),
    actions         varchar(255)
);

alter table notification_actions
    owner to najdiprevoz;


create table if not exists password_reset_tokens (
    id bigserial not null
        constraint password_reset_tokens_pkey
            primary key,
    expiry_date timestamp not null,
    token varchar(255) not null
        constraint uk_71lqwbwtklmljk3qlsugr1mig
            unique,
    user_id bigint not null
        constraint uk_la2ts67g4oh2sreayswhox1i6
            unique
        constraint fkk3ndxg5xp6v7wd4gjyusp15gq
            references users
);

alter table password_reset_tokens
    owner to najdiprevoz;



INSERT INTO public.cities(name)
VALUES ('Skopje'),
       ('Struga'),
       ('Strumica'),
       ('Ohrid'),
       ('Debar'),
       ('Gostivar'),
       ('Resen'),
       ('Prilep'),
       ('Bitola'),
       ('Tetovo'),
       ('Pehcevo'),
       ('Kicevo'),
       ('Mavrovo'),
       ('Kumanovo'),
       ('Veles'),
       ('Gevgelija'),
       ('Negotino'),
       ('Kavadarci'),
       ('Stip'),
       ('Probistip'),
       ('Kocani'),
       ('Sveti Nikole'),
       ('Delcevo'),
       ('Makedonski brod'),
       ('Makedonska Kamenica'),
       ('Vinica'),
       ('Valandovo'),
       ('Krusevo'),
       ('Radovish'),
       ('Kriva Palanka'),
       ('Berovo'),
       ('Demir kapija'),
       ('Kratovo'),
       ('Demir hisar'),
       ('Dojran');

insert into public.authorities(authority)
VALUES ('ROLE_USER');
insert into public.authorities(authority)
VALUES ('ROLE_ADMIN');

