create table if not exists sms_trip_notifications
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created_on      timestamptz,
    from_location   bigint not null references cities(id),
    to_location     bigint not null references cities(id),
    phone_number    TEXT not null,
    valid_until     timestamptz not null
);

alter table sms_trip_notifications
    owner to najdiprevoz;


create table if not exists sent_sms_messages
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    sent_on timestamptz,
    message_body      text,
    sms_trip_notification_id  int  not null REFERENCES sms_trip_notifications(id),
    trip_id int not null references trips(id)
);

alter table sent_sms_messages
    owner to najdiprevoz;


