export const columnPrettyName = new Map();
columnPrettyName.set('allowedActions', 'ACTIONS');
columnPrettyName.set('requesterName', 'REQUESTER');
columnPrettyName.set('fromLocation', 'FROM');
columnPrettyName.set('toLocation', 'TO');
columnPrettyName.set('to', 'TO');
columnPrettyName.set('from', 'FROM');
columnPrettyName.set('totalSeats', 'TOTAL_SEATS');
columnPrettyName.set('pricePerHead', 'PRICE_PER_HEAD');
columnPrettyName.set('status', 'STATUS');
columnPrettyName.set('departureTime', 'DEPARTURE');
columnPrettyName.set('requestStatus', 'REQUEST_STATUS');
columnPrettyName.set('driverName', 'DRIVER');
columnPrettyName.set('driver', 'DRIVER');
columnPrettyName.set('tripId', 'TRIP_ID');
columnPrettyName.set('rideStatus', 'RIDE_STATUS');
