export const columnPrettyName = new Map();
columnPrettyName.set('allowedActions', 'Actions');
columnPrettyName.set('requesterName', 'Requester');
columnPrettyName.set('fromLocation', 'From');
columnPrettyName.set('toLocation', 'To');
columnPrettyName.set('to', 'To');
columnPrettyName.set('from', 'From');
columnPrettyName.set('totalSeats', 'Total Seats');
columnPrettyName.set('pricePerHead', 'Price per head');
columnPrettyName.set('status', 'Status');
columnPrettyName.set('departureTime', 'Departure');
columnPrettyName.set('requestStatus', 'Request Status');
columnPrettyName.set('driverName', 'Driver');
columnPrettyName.set('driver', 'Driver');
columnPrettyName.set('tripId', 'Trip ID');
columnPrettyName.set('rideStatus', 'Ride Status');
